Добавлена папка ludmila_pshenichnikova в директорию homework
eugene-okulik/Ludmila pull request #1
Opened 2024-06-18 13:37 UTC by GPMila79

Добавлена папка ludmila_pshenichnikova в директорию homework с пустым текстовым файлом, а также были внесены изменения в файл README.md - добавлено "hello 1234"

2024-06-18 13:40 UTC, GPMila79 commented
Добавился только пустой файл в мою ветку, изменения которые я пыталась сделать в ветке main не сохранились, видимо потому что не было доступа на внесение изменений.

2024-06-18 14:42 UTC, eugene-okulik requested changes
Как написано в задании, первый вариант не принимаю и указываю, что нужны изменения. Это просто для того, чтобы нам попрактиковаться в том, как мы будем взаимодействовать.  
Добавь в пустой файл какую-нибудь букву, коммитай и запушивай.

2024-06-18 14:43 UTC, eugene-okulik commented
> Добавился только пустой файл в мою ветку, изменения которые я пыталась сделать в ветке main не сохранились, видимо потому что не было доступа на внесение изменений.

Да, с веткой main мы не работаем. Все изменения вносятся в другие ветки, а потом вливаются в ветку main.

2024-06-18 16:02 UTC, GPMila79 commented
Added a new letter in a free file

2024-06-19 07:07 UTC, eugene-okulik approved these changes

2024-06-19 07:07 UTC, merged