Added homework_5
eugene-okulik/Ludmila pull request #4
Opened 2024-06-23 23:55 UTC by GPMila79

Added homework_5

2024-06-24 09:14 UTC, eugene-okulik requested changes

2024-06-24 09:14 UTC, eugene-okulik commented on homework/ludmila_pshenichnikova/homework_5/python_basic_3.py
> +print(name, last_name, city, phone, country)
В питоне считается не рекомендуемым обращаться к элементам списка по идентификатору. Желательно всегда каким-то образом пытаться этого избежать. И в этой ситуации удобнее всего это сделать с помощью распаковки. Я показывал её в занятии.

2024-06-24 09:14 UTC, eugene-okulik commented on homework/ludmila_pshenichnikova/homework_5/python_basic_3.py
> +print(my_text.format(a, b, c, d, e, f))
А здесь избежать обращений по идентификаторам можно с помощью `join`, это я тоже показывал.

2024-06-24 14:59 UTC, GPMila79 commented
Changed two tasks (1 and 3), delete index

2024-06-25 09:41 UTC, eugene-okulik approved these changes

2024-06-25 09:41 UTC, merged